### PR TITLE
[newrelic-logging] Configurable Kubernetes filter HTTP buffer size

### PR DESCRIPTION
**Pull request by rlees85**
# Allow Kubernetes filter http buffer size to be configured since many pod templates now exceed 32k.

#### Is this a new chart
No

#### What this PR does / why we need it:
Allow Kubernetes filter http buffer size to be configured since many pod templates now exceed 32k.

#### Which issue this PR fixes
Cannot find open issue. Fixes issue where logs are dropped for certain pods that contain a large template. The following is in the newrelic logging agent logs:
```
[2021/11/04 13:49:51] [ warn] [http_client] cannot increase buffer: current=32000 requested=64768 max=32000
```
Fixes the issue without having to maintain an entire custom filters block in Helm values.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)

### CODE REVIEW

**Comment by rlees85** [comment]
Related: https://github.com/newrelic/helm-charts/pull/570

**Comment by rediphone** [comment]
Hi there, this would be helpful for me, please could we get this in I have problems with logs that this would resolve - thanks!

**Comment by rediphone** [comment]
Hi guys, sorry to chase but it would be great to get this in - i have an issue which this PR would resolve. if there is a problem please can we discuss what this issue is

thanks very much

**Comment by rediphone** [comment]
any possibility to  progress this please 
@jsubirat
@tejunior

**Comment by roobre** [comment]
Hey there,

Just my two cents here, I think we might benefit to a more flexible solution that allows users to define arbitrary options in the `values.yaml` that get appended to the filters. This should scale better and would not require users to open a PR for each new Fluentbit flag they want to change.

WDYT @newrelic/logging ?

**Review by tejunior — APPROVED** [review]

**Comment by tejunior** [comment]
More resources about this issue:
https://github.com/fluent/fluent-bit/issues/2033
https://github.com/fluent/fluent-bit/issues/3112

**Comment by rlees85** [comment]
@roobre I also like this idea, but sadly I don't think that PR will permit it since we are wanting to add settings to an existing (Kubernetes) filter rather than adding new filter blocks. I am not sure if fluentd/fluentbit stacks "same" filter blocks.

**Pull request merged**
