### PR TITLE
[newrelic-logging] Added ability to provide annotations for ServiceAccount & DaemonSet

### PR DESCRIPTION
**Pull request by gonzalobarbitta**
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)

### CODE REVIEW

**Review by roobre — APPROVED** [review]

**Comment by roobre** [comment]
@jsubirat @tejunior Any comments on this? Should be simple enough, we have merged similar PRs in #273  and #275 

@gonzalobarbitta Please rebase master whenever you have a moment

**Comment by gonzalobarbitta** [comment]
Thanks @roobre , I just rebased master.

**Comment by gonzalobarbitta** [comment]
@jsubirat  @tejunior any thoughts as to when will this be reviewed? Thanks

**Comment by roobre** [comment]
Merging as I don't see much reason to keep it open given the simplicity of the change.

**Pull request merged**
