### PR TITLE
[newrelic-infrastructure]: Make securityContext a templated value for windows infra daemonset

### PR DESCRIPTION
**Pull request by goody44**
#### Is this a new chart
No

#### What this PR does / why we need it:
Deploying the Windows infra chart to GKE results in the error below. If the `spec.containers[0].securityContext` value is removed then it works fine. This PR makes the securityContext field a templated value.
(combined from similar events): Error creating: admission webhook "windows.common-webhooks.networking.gke.io" denied the request: spec.containers[0].securityContext: Invalid value: v1.SecurityContext{Capabilities:(*v1.Capabilities)(nil), Privileged:(*bool)(0xc000696a3c), SELinuxOptions:(*v1.SELinuxOptions)(nil), RunAsUser:(*int64)(nil), RunAsGroup:(*int64)(nil), RunAsNonRoot:(*bool)(nil), ReadOnlyRootFilesystem:(*bool)(nil), AllowPrivilegeEscalation:(*bool)(nil), ProcMount:(*v1.ProcMountType)(nil)}: Windows does not support this field. Note that defaults may be allowed for compatibility.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ x] Chart Version bumped
- [ x] Variables are documented in the README.md
- [ x] Title of the PR starts with chart name (e.g. `[mychartname]`)

### CODE REVIEW

**Comment by paologallinaharbur** [comment]
Thanks @goody44 for the contribution.

It looks good, I will proceed to merge it once license agreements are signed, 

Can you also rebase on master?

**Review by paologallinaharbur — APPROVED** [review]

**Comment by goody44** [comment]
Thanks for the review! I've signed the CLA and rebased, although I may have messed that up as the diff is now showing the re-based changes.

**Comment by paologallinaharbur** [comment]
There are different way to solve this issue.

I would suggest to rebase using the interactive mode over the *updated* fork
Assuming `origin` is pointing to this repository
`git fetch -a origin`
`rebase -i origin/master` dropping the commits that are not yours.
`git push fork yourBranchName --force` to update the history

Or you can reopen the PR copying manually the changes

**Comment by goody44** [comment]
Sorry for the delay and thanks for the instructions. I've rebased it properly now

**Review by paologallinaharbur — APPROVED** [review]

**Pull request merged**
