### PR TITLE
fix: add or document `podAnnotations` value

### PR DESCRIPTION
**Pull request by MarcusNoble**
#### Is this a new chart
No

#### What this PR does / why we need it:
There was inconsistencies between the charts as to which supported providing custom pod annotations and which didn't. There also wasn't any reference to this value in any of the documentation.
This PR adds `podAnnotations` as a value to all charts and includes it in the documentation.

#### Which issue this PR fixes
N/a

#### Special notes for your reviewer:
As this covers multiple charts I'm not sure how you want me to handle the PR title and versioning etc. so please advise :)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [x] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[mychartname]`)

### CODE REVIEW

**Comment by MarcusNoble** [comment]
I'd like so guidence on how to handle chart versions in this PR.

**Comment by ardias** [comment]
Marcus, aren't some changes in this PR already present in your other PR's? I'm seeing the same change to serviceAccount annotations here as in #130

**Comment by MarcusNoble** [comment]
Oh you're right. I must have forked from the wrong branch. Let me clean that up.

**Comment by MarcusNoble** [comment]
Fixed. 
Please advise on what you'd like the chart versions set to.

**Comment by ardias** [comment]
We usually bump the Minor chart version when we introduce some change, so for each of the charts you've changed, bump it on the Minor version (major.Minor.patch)

**Comment by paologallinaharbur** [comment]
Moreover we should have One PR per chart in order to make easier, reviewing and merging

**Comment by paologallinaharbur** [comment]
Can you add in the title of the pr the chart name between [..]?

**Comment by MarcusNoble** [comment]
@paologallinaharbur I've split this into multiple PRs:
* https://github.com/newrelic/helm-charts/pull/217
* https://github.com/newrelic/helm-charts/pull/218
* https://github.com/newrelic/helm-charts/pull/219
* https://github.com/newrelic/helm-charts/pull/220
* https://github.com/newrelic/helm-charts/pull/221

**Pull request closed without merging**
