### PR TITLE
Configurable image pull secrets for newrelic-logging, nri-kube-events, nri-metadata-injection, nri-prometheus

### PR DESCRIPTION
**Pull request by mschenk42**
#### Is this a new chart
no

#### What this PR does / why we need it:
To allow for configuring image pull secrets in all charts for private registries. This will allow for storing images in private registries to avoid Docker Hub rate pull limits being put in place on November 1st.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

I would like version bumps for charts changed but I don't fully understand the process for how to do that.

- [ ] Chart Version bumped
- [X ] Variables are documented in the README.md
- [ X] Title of the PR starts with chart name (e.g. `[mychartname]`)

### CODE REVIEW

**Comment by mschenk42** [comment]
Hi, is possible to get a review on this? Trying to get this done for the November 1st Docker pull limits.

**Comment by mschenk42** [comment]
Hi  @jorik @paologallinaharbur @ardias @dbrota @gsanchezgavier, would it be possible ti get a code review and if things are good a release of the nri-bundle chart with the latest charts?

**Comment by gsanchezgavier** [comment]
Hi @mschenk42  thanks for contributing. Related to how the ci/cd pipeline manages releases the changes for each chart should be submitted in a different PR. I don't see any other comment to add , the changes looked good to me.

**Comment by mschenk42** [comment]
ok, will do, closing this PR and will submit new ones for each chart

**Pull request closed without merging**
