### PR TITLE
Windows FluentBit Helm Chart

### PR DESCRIPTION
**Pull request by andrew-lozoya**
Since v1.5.0, Fluent Bit supports deployment to Windows pods. New Relic offers a [Fluent Bit](https://fluentbit.io/) output [plugin](https://github.com/newrelic/newrelic-fluent-bit-output) to easily forward your logs to [New Relic Logs](https://docs.newrelic.com/docs/logs/new-relic-logs/get-started/introduction-new-relic-logs). This plugin is also provided in a [standalone Docker image](https://github.com/andrew-lozoya/newrelic-fluent-bit-output/blob/master/Dockerfile) that can be installed in a [Kubernetes](https://kubernetes.io/) cluster in the form of a [DaemonSet](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/), which we refer as the Kubernetes plugin.

This document explains how to install it in your cluster, either using a [Helm](https://helm.sh/) chart (recommended). Starting with chart version 2.7.1, chart deploys the daemonset on windows nodes which collects std{out;err} logs of the containers running on windows nodes.

### CODE REVIEW

**Comment by paologallinaharbur** [comment]
@bmcfeely Can you have a look to this PR?

**Comment by paologallinaharbur** [comment]
@andrew-lozoya Is this a whole new chart?

Also newrelic-infrastructure support both linux and windows. 
If possible I believe we should follow the same approach having a single chart configurable

**Comment by bmcfeely** [comment]
@mshamota-nr can someone from Sunstone take a look? Thank  you!

**Comment by casey-robertson** [comment]
Chiming in as an end-user.... would love to see this get implemented for Windows K8s nodes!

**Comment by paologallinaharbur** [comment]
Can you add in the title of the pr the chart name between [..]

**Comment by mshamota-nr** [comment]
Hi, our @hero will review it. Thanks! Ticket: https://newrelic.atlassian.net/browse/LOGGING-3846

**Comment by tejunior** [comment]
Hi @andrew-lozoya this PR got forgot ... LGTM, could you update with master and fix the Lint?

**Comment by tejunior** [comment]
Closed due inactivity

**Comment by jsubirat** [comment]
Sorry, we closed this PR accidentally. Reopening it again

**Comment by jsubirat** [comment]
Many thanks for your contribution @andrew-lozoya , really appreciated! As we discussed offline, I merged your changes into our existing `newrelic-logging` Helm chart in this other PR: https://github.com/newrelic/helm-charts/pull/509

**Pull request closed without merging**
