### PR TITLE
add custom interval to scrape metrics

### PR DESCRIPTION
**Pull request by adimania**
#### Is this a new chart
No
#### What this PR does / why we need it:
This PR lets us set the interval on nri-kubernetes-definition.yml which can help customize the frequency of the datapoints that are sent to Newrelic.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)

### CODE REVIEW

**Comment by gsanchezgavier** [comment]
Hi @adimania  thanks for your contribution , this is related to a FR described on #344 . 

We are thinking to follow a different approach for this described [here](https://github.com/newrelic/nri-kubernetes/issues/83) that would cause a breaking change if we merge your proposed solution here. 

So event if this is not a breaking change now it would make that our proposed solution to this be breaking change.

**Comment by adimania** [comment]
Hi @gsanchezgavier. That is awesome. I am happy to see that work is being done in this direction. 
Do you have an ETA for this feature? I would be happy to close this PR in favour of community's decision to move the files in /etc.

**Comment by gsanchezgavier** [comment]
not sure about ETA this still need to be prioritized.

**Comment by mangulonr** [comment]
Hi @adimania 

Thanks for your contribution, we're planning to implement this feature on FY22 Q2.

I will updated you once the feature is released.

Regards

**Comment by paologallinaharbur** [comment]
Closing this due to the discussion above

**Pull request closed without merging**
