### PR TITLE
[newrelic-logging] Allow configuration of kubernetes filter Buffer_Size param

### PR DESCRIPTION
**Pull request by Voziv**
#### What this PR does / why we need it:

We were experiencing the error `[2021/11/04 13:49:51] [ warn] [http_client] cannot increase buffer: current=32000 requested=64768 max=32000` on our newrelic logging pods.

Increasing the buffersize on the kubernetes filter to 64k solved this issue.

I've added a helm chart value for configuring this setting.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)

### CODE REVIEW

**Comment by Voziv** [comment]
Sorry, forgot to add the mentions for the chart maintainers on this PR:
@jsubirat
@tejunior
@jodstrcil
@edmocosta
@Noly
@danybmx

**Comment by rlees85** [comment]
We are hitting this problem as well. I think as clusters and services grow in complexity so will many others. Why has nobody reviewed this simple change since November? We don't really want to maintain entire filter blocks in our configuration.

**Comment by rlees85** [comment]
@Voziv are you interested in fixing the merge conflicts or should I fork/create my own PR?

**Comment by Voziv** [comment]
@rlees85 I'm testing the new chart. I believe this PR was made obsolete by #593 as it seems all the config has moved into values.yaml.

I'll update this once I have the new chart deployed with the tweaks this PR implements to confirm that nothing else needs to change.

**Comment by Voziv** [comment]
Can confirm the changes from the new chart are sufficient to fix this issue.

Here's a simple diff for adding in the buffer size change to your values: @rlees85 

```diff
    filters: |
      [FILTER]
          Name                kubernetes
          Match               kube.*
          # We need the full DNS suffix as Windows only supports resolving names with this suffix
          # See: https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#dns-limitations
          Kube_URL            https://kubernetes.default.svc.cluster.local:443
          K8S-Logging.Exclude ${K8S_LOGGING_EXCLUDE}
+         Buffer_Size         64k
      [FILTER]
          Name           record_modifier
          Match          *
          Record         cluster_name ${CLUSTER_NAME}
    lowDataModeFilters: |
      [FILTER]
          Name           kubernetes
          Match          kube.*
          # We need the full DNS suffix as Windows only supports resolving names with this suffix
          # See: https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#dns-limitations
          Kube_URL       https://kubernetes.default.svc.cluster.local:443
          K8S-Logging.Exclude ${K8S_LOGGING_EXCLUDE}
+         Buffer_Size         64k
          Labels         Off
          Annotations    Off
      [FILTER]
          Name           nest
          Match          *
          Operation      lift
          Nested_under   kubernetes
      [FILTER]
          Name           record_modifier
          Match          *
          Record         cluster_name ${CLUSTER_NAME}
          Allowlist_key  container_name
          Allowlist_key  namespace_name
          Allowlist_key  pod_name
          Allowlist_key  stream
          Allowlist_key  log
```

**Comment by rlees85** [comment]
Thanks - I was hoping to be able to tweak the buffer size without having to declare the entire filters section in the values. I will raise a PR based on your original approach and see if the NR team are willing to accept it.

**Pull request closed without merging**
