### PR TITLE
[nri-bundle] Bump subcharts versions

### PR DESCRIPTION
**Pull request by AdrienKuhn**
#### Is this a new chart

No

#### What this PR does / why we need it:

Upgrade subcharts versions
* nri-prometheus
* nri-metadata-injection
* nri-kube-events
* newrelic-logging

#### Which issue this PR fixes

N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[mychartname]`)

### CODE REVIEW

**Comment by AdrienKuhn** [comment]
Subcharts tarballs are supposed to be ignored according to https://github.com/newrelic/helm-charts/blob/master/.gitignore#L36

Do you want me to clear the `charts` subdirectory ?

**Comment by douglascamata** [comment]
@AdrienKuhn it would be great, is that still works 😅 

Thanks again.

**Comment by AdrienKuhn** [comment]
@douglascamata Actually it doesn't seems to work as we are referencing the local charts in the [requirements.yaml file](https://github.com/newrelic/helm-charts/blob/master/charts/nri-bundle/requirements.yaml#L3)

**Comment by douglascamata** [comment]
@AdrienKuhn ah yes. Feel free to update to the remote reference instead then. I think it will be even better like so.

**Comment by AdrienKuhn** [comment]
@douglascamata 

I'm not able to make it work...
I will try to investigate in the next days and I will open a new PR.

**Pull request merged**
