### PR TITLE
[super-agent-deployment] fixes

### PR DESCRIPTION
**Pull request by gsanchezgavier**
#### Is this a new chart
No
#### What this PR does / why we need it:
Fixes issues founded during manual testing
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes rbac missing
  - fixes CM of sub-agent naming

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)

### CODE REVIEW

**Review by kang-makes — APPROVED** [review]
TIL

Thanks!

**Comment by gsanchezgavier** [comment]
upgrade path is faling due to previous broken version with the updated nightly image

**Review by sigilioso — APPROVED** [review]
LGTM

**Review by kang-makes — APPROVED** [review]
Thanks for taking care of this.

LGTM

**Pull request merged**
