### PR TITLE
[newrelic-pixie] Switch staging endpoint to new ingest path.

### PR DESCRIPTION
**Pull request by cwildman**
#### Is this a new chart
No

#### What this PR does / why we need it:
Switches the staging endpoint to use the new ingest path.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
@douglascamata 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[mychartname]`)

### CODE REVIEW

**Review by fryckbos — APPROVED** [review]
Looks good to me.

**Review by fryckbos — CHANGES_REQUESTED** [review]
The appVersion should not have been bumped.

**Comment by fryckbos** [comment]
I've added the change of the staging endpoint in this PR: https://github.com/newrelic/helm-charts/pull/495

**Comment by gsanchezgavier** [comment]
superseded by #495

**Pull request closed without merging**
