### PR TITLE
[nri-kube-events] Fix 'kube-events' container restarts due to '/tmp' …

### LINKED ISSUE #72: [nri-kube-events] attempting to write warnings to RO filesystem
`nri-kube-events`'s `kube-events` container keeps crashing every few minutes as a watch warning causes the service to try to write to `/tmp`, which is a readonly filesystem. I am not sure if this is necessarily a bug in `kube-events` or the container should just be updated to allow it to write to a tmpfs like the side-car `infra-agent` container already can.

**Version of Helm and Kubernetes**

```
$ kubectl version
...
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
$ helm version
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

**Which chart?**

`nri-kube-events` / `kube-events`

**What happened?**

When any of the watchers emit a warning, it attempts to log it to `/tmp`. This is a read-only filesystem which causes the container to crash and restart.

```
W0623 14:41:44.507228       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.Event ended with: The resourceVersion for the provided watch is too old.
log: exiting because of error: log: cannot create log: open /tmp/nri-kube-events.newrelic-events-nri-kube-events-c6bfbd6ff-6bm5s.nri-kube-events.log.WARNING.20200623-144144.1: read-only file system
```

**What you expected to happen?**

`kube-events` warnings shouldn't cause the container to restart. This should either be made into a writable directory or `kube-events` should only send warnings to stdout.

**How to reproduce it?**

This is just a generic Rancher deployed K8s cluster on v1.17.4

### PR DESCRIPTION
**Pull request by rbabyuk**
…RO fylesystem

#### Is this a new chart
no
#### What this PR does / why we need it:
kube-events container is restarted every 8-10m(?) due to 'cannot write log file to /tmp/newrelic...log fylesyste, is read-only'

#### Which issue this PR fixes
  - fixes #72

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)

### CODE REVIEW

**Comment by roobre** [comment]
Hi @rbabyuk ,

Thank you veryu much for your contribution, and apologies for the delay getting through this. 

This looks completely alright to me, I'd be more than happy to merge if you could solve conflicts with the current branch (as well as sign the CLA).

**Comment by roobre** [comment]
Hello again,

Upon further investigation we have found out that logging to `/tmp` was never intended in the first place. This was a bug-ish behavior of the k8s client library, which has now been resolved. I'll close this when https://github.com/newrelic/nri-kube-events/issues/19 gets merged.

Thanks!

**Comment by rbabyuk** [comment]
Hey @roobre , sure, let me solve conflicts first.
But I am not sure why CLA is not marked as signed, I am puzzled.

**Comment by roobre** [comment]
Hi @rbabyuk,
I'd wait for a few days to see if we encounter any blocker merging the upstream fix (which I don't expect to, but one never knows). If for some reason the fix needs to be delayed I'd go for merging this as a temporary fix.

**Comment by roobre** [comment]
Hi again @rbabyuk,
I'd like to thank you again for your contribution and bringing our attention to this issue. We have merged a version bump in nri-kube-events that prevents the k8s core library from writing to `/tmp`, as it is the expected behavior from our point of view.
If this doesn't fix the issue on your setup please contact us again so we can further study the problem.

**Pull request closed without merging**
