### PR TITLE
[nri-bundle] bump nri-metadata-injection and infra-operator

### PR DESCRIPTION
**Pull request by nwsparks**
#### Is this a new chart

No

#### What this PR does / why we need it:

Increments sub chart versions to capture changes from:

https://github.com/newrelic/helm-charts/pull/530

#### Which issue this PR fixes
  - fixes https://github.com/newrelic/helm-charts/issues/460

#### Special notes for your reviewer:

Incremented minor version of this chart since subcharts are adding new functionality, hopefully that was correct.

Putting in draft until #530  is merged

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)

### CODE REVIEW

**Comment by roobre** [comment]
Hi @nwsparks, thanks again for the PR, that was fast!
I assume this is the final PR for this series (adding the missing `pullSecrets`), is this correct?

**Comment by nwsparks** [comment]
@roobre no problem! Thank you for looking at my PR's.

Yes correct trying to get these into the bundle. Not sure if this PR is correct, but though I'd give it a shot. Had some trouble keeping up with the merges and getting ci to pass but it seems to be looking better now.

**Comment by nwsparks** [comment]
@roobre feel free to close this if you prefer a different approach or it is not how you normally do it.

**Comment by roobre** [comment]
No need to change anything @nwsparks, this is exactly how we normally do it!

However I might need to hold this one a bit, as due to some reliability incidents we have decided to hold delicate releases until next Monday. We should be fine merging this then. I hope it's not a big inconvenience :)

**Review by roobre — APPROVED** [review]

**Comment by nwsparks** [comment]
No problem at all, thanks!

**Comment by roobre** [comment]
We're good to merge this now. Thanks again @nwsparks!

**Pull request merged**
